import type { MetaArgs } from "react-router";
import HostedPolicyLayout, { type PolicySection } from "../components/HostedPolicyLayout";
import { LINK_CLASS } from "../components/docs-tokens";
import { siteMeta, sitePath } from "../lib/site-meta";

export function meta({ location }: MetaArgs) {
  return siteMeta(location.pathname, {
    title: "Hosted terms of service — Dormouse",
    description: "Terms for Dormouse Hosted accounts and subscriptions, operated by DiffPlug LLC.",
  });
}

export const TERMS_SECTIONS: PolicySection[] = [
  { id: "service", title: "The service", body: <>
    <p>These terms govern Dormouse Hosted, provided and sold by DiffPlug LLC: the account service at hosted.dormouse.sh and the paid subscription that adds managed voices and the managed Relay for Pocket. You must be legally able to enter this agreement. If you act for an organization, you must have authority to bind it. The subscription provisions apply to purchases made when paid subscriptions become available.</p>
    <p>The <a className={LINK_CLASS} href={sitePath("/hosted")}>Hosted page</a> describes what a subscription includes and what it costs. An account alone is free and grants no paid features.</p>
    <p>The Dormouse software and self-hosted components remain subject to their own software licenses. These terms do not change those licenses or require a Hosted account to use local terminals, and nothing Dormouse ships free is moved behind a subscription.</p>
  </> },
  { id: "account", title: "Your account", body: <>
    <p>Use an email address or provider account you are authorized to use. Protect those accounts and your devices, and tell us if you believe someone is using your Hosted account without permission.</p>
    <p>You are responsible for activity you authorize through your account. Provider sign-in depends on the provider’s availability and policies. Keep access to at least one connected sign-in method: account merging, automatic recovery, and a sign-out-everywhere control are not available. Connecting a provider is an explicit account action; matching email addresses alone do not merge accounts.</p>
    <p>Our <a className={LINK_CLASS} href={sitePath("/privacy")}>privacy policy</a> explains how we handle account information.</p>
  </> },
  { id: "subscriptions", title: "Subscriptions and payment", body: <>
    <p>A subscription is billed monthly or yearly, at the price shown when you buy it, in US dollars. DiffPlug LLC is the seller and uses Stripe Billing and Stripe-hosted Checkout to process payments and manage subscriptions. We are responsible for the subscription, refunds, and applicable sales tax or VAT obligations. Checkout shows the total, including any applicable tax, before you authorize payment.</p>
    <p>Every plan renews automatically at the end of each period until you cancel. There is no free trial; the refund below takes its place.</p>
    <p>A subscription covers one individual, including that person’s work use, with no per-device charge. It may not be shared, resold, or transferred to another person. Device enrollment and usage limits are described below. For shared accounts, multiple users, or organization-level features, email <a className={LINK_CLASS} href="mailto:support@dormouse.sh">support@dormouse.sh</a>.</p>
    <p>If a renewal payment fails, the paid features stop until a payment succeeds. Dormouse keeps working in the meantime, with spoken alarms in your system voice.</p>
  </> },
  { id: "cancellation", title: "Cancellation and refunds", body: <>
    <p>You can cancel at any time from the billing portal in your account. Cancelling stops future renewals; you keep the paid features until the end of the period you already paid for. If you cannot sign in or use the portal, contact <a className={LINK_CLASS} href="mailto:support@dormouse.sh">support@dormouse.sh</a> to cancel. We may verify that you own the subscription, but do not require you to recover account access to cancel it.</p>
    <p>Ask within 30 days of your first Hosted subscription payment, or of any yearly renewal, and we will refund that payment in full, including tax we collected on it. Monthly renewals are not covered by this voluntary guarantee. Changing plans or cancelling and subscribing again does not restart the first-payment window. A full refund ends the subscription and its paid features straight away, and a founding refund returns the seat to its cohort. Email <a className={LINK_CLASS} href="mailto:support@dormouse.sh">support@dormouse.sh</a> to ask.</p>
    <p>This guarantee is in addition to the refunds for discontinuation or material service reductions below and any rights or remedies the law where you live gives you, including cancellation, withdrawal, and remedies for defective or undelivered services. Those rights are not limited to 30 days by these terms. We issue refunds to the original payment method where possible; your bank or payment provider controls when the credit appears.</p>
  </> },
  { id: "withdrawal", title: "EEA and UK consumer withdrawal", body: <>
    <p>If you are a consumer in the European Economic Area or United Kingdom, you may withdraw from your initial Hosted subscription contract without giving a reason within 14 days after the contract is made. Send an unambiguous statement to <a className={LINK_CLASS} href="mailto:support@dormouse.sh">support@dormouse.sh</a> or by post to DiffPlug LLC, 447 Sutter St Ste 405, San Francisco, CA 94108, United States, before that period ends. We do not require a particular form, account access, or a reason.</p>
    <p>You can also use “Withdraw from contract” on your Hosted account’s billing page during the withdrawal period, then confirm your withdrawal. We will send you an acknowledgement on a durable medium, such as email, with your statement and the date and time it was submitted. Withdrawal ends the current contract; ordinary cancellation of renewal keeps access through the paid period.</p>
    <p>For that withdrawal, we will refund all payments received for the subscription, including collected tax, without undue delay and within 14 days after receiving your notice. We use the original payment method unless you expressly agree otherwise, and charge no refund fee. Access ends on withdrawal. Starting to use Hosted immediately does not waive this right, and we do not deduct a charge for use during this withdrawal period. Our separate 30-day guarantee and any longer statutory rights remain available.</p>
    <p>You may use this optional withdrawal form by email or post: “To DiffPlug LLC, 447 Sutter St Ste 405, San Francisco, CA 94108, United States; support@dormouse.sh: I give notice that I withdraw from my contract for Dormouse Hosted. Ordered on: ____. Name: ____. Address: ____. Date: ____. Signature, only if sent on paper: ____.” Your account email or order reference helps us locate the purchase, but is not a required formality for giving notice.</p>
  </> },
  { id: "founding", title: "Founding prices", body: <>
    <p>A founding subscription is a yearly plan sold at a launch price, in cohorts of 100. When a cohort sells out the founding price rises, and founding closes when it reaches the list price.</p>
    <p>Your base yearly subscription price in US dollars is locked for as long as that subscription stays active. Applicable taxes may change. If a founding renewal payment fails, you have 30 days from the failed renewal to fix it and keep the locked price; this preserves the price, not paid access during nonpayment. After that, subscribing again is at the list price, as it is after you cancel and the paid period ends. A billing-provider migration or a payment failure caused by us does not forfeit your locked price; we will give you a reasonable opportunity to restore payment.</p>
    <p>A founding badge is cosmetic. It grants nothing beyond the plan itself.</p>
  </> },
  { id: "fair-use", title: "Fair use", body: <>
    <p>Managed voices allow 500 requests per subscriber per UTC day. Attempts sent to the speech provider count even if the provider fails; playing a cached clip does not. Past the limit, Dormouse speaks in your system voice until the next UTC day. The managed Relay allows up to 32 enrolled copies of Dormouse per account; the standalone app and VS Code extension count separately. There is no additional per-device fee.</p>
    <p>The Relay also limits connection attempts and requests to protect availability and prevent abuse. We may act immediately against abuse or security threats. Material reductions to the paid service remain subject to the notice and refund provisions below.</p>
  </> },
  { id: "managed-voices", title: "Managed voices and ElevenLabs", body: <>
    <p>ElevenLabs supplies the speech generation used by managed voices. You must be at least 18 years old, or the age of legal majority where you live if higher, to use managed voices. Use them only through Dormouse, for its alarms. Do not extract, resell, sublicense, or redistribute the speech service or your credentials.</p>
    <p>For managed voices and the resulting audio, you must comply with the restrictions, obligations, and prohibitions concerning use in the <a className={LINK_CLASS} href="https://elevenlabs.io/terms-of-use">ElevenLabs Terms of Service</a> and <a className={LINK_CLASS} href="https://elevenlabs.io/use-policy">Prohibited Use Policy</a>, which are incorporated into this agreement for that purpose. This includes their restrictions on harmful or deceptive impersonation, infringement, abuse, bypassing safeguards, and using the service or its output to train AI models or develop competing products. Do not send protected health information subject to HIPAA through managed voices. Government entities, as defined in the Prohibited Use Policy, may not use managed voices without ElevenLabs’ prior written authorization; contact us before using them on behalf of such an entity.</p>
    <p>You must have the rights and permissions needed for the labels you send for speech generation. You grant DiffPlug, ElevenLabs, and ElevenLabs’ affiliates and subcontractors a non-exclusive right to process and use those labels and the resulting audio to provide and support managed voices, as described in our <a className={LINK_CLASS} href={sitePath("/privacy")}>privacy policy</a>. This permission does not transfer ownership of your content.</p>
    <p>DiffPlug is not ElevenLabs’ agent or partner and is not in a joint venture with ElevenLabs. You must not hold yourself out as ElevenLabs’ agent, partner, or joint venturer through your use of managed voices. ElevenLabs is an intended third-party beneficiary of these terms as they relate to managed voices and may enforce those provisions.</p>
    <p>DiffPlug provides support for your Hosted subscription. Your payments, cancellation, refunds, and disputes with DiffPlug remain governed by these Hosted terms. Nothing in this section reduces your mandatory consumer rights. We will notify you of material updates to the incorporated provider requirements through the changes process below, obtain renewed agreement where required, and pass on provider notices that affect your use. If a provider requirement prevents us from continuing managed voices under your agreed terms, the service-reduction and refund provisions below apply.</p>
  </> },
  { id: "acceptable-use", title: "Acceptable use", body: <>
    <p>Do not use the service unlawfully, impersonate others, access accounts without authorization, send unwanted messages, interfere with other users, or bypass authentication, rate limits, or other security controls. Do not use the service to distribute malware or attack third parties.</p>
    <p>Good-faith security reports are welcome through our <a className={LINK_CLASS} href={sitePath("/security")}>security reporting process</a>. Avoid accessing other people’s data or disrupting service while investigating an issue.</p>
  </> },
  { id: "availability", title: "Availability and account closure", body: <>
    <p>We may change features, interrupt operation for maintenance, or discontinue the service. We do not promise uninterrupted availability or a particular future feature. When managed voices are unavailable, Dormouse speaks in your system voice.</p>
    <p>If we permanently discontinue Hosted, we will stop renewals and refund prepaid fees for the unused portion of your subscription, including the corresponding tax we collected. We will give at least 30 days’ advance notice unless a legal or urgent security requirement prevents it; in that case we will notify you as soon as reasonably possible. The Relay is source-available and its <a className={LINK_CLASS} href={sitePath("/self-host")}>self-hosting guide</a> is published if you want to operate your own Relay. Self-hosting does not replace your refund.</p>
    <p>If we materially reduce your paid service during a prepaid term, we will give the same advance notice and allow you to end the subscription with a refund for its unused portion. If we permanently end your paid access for a reason other than your material breach, we will also refund the unused portion. These refunds are calculated from when the paid access ends and are not restricted by the 30-day voluntary guarantee.</p>
    <p>We may restrict or suspend an account to address abuse, a security issue, a legal requirement, or a material violation of these terms. Where practical, we will explain the reason and provide a way to contact us; urgent protective action may come first.</p>
    <p>You may stop using the service at any time. Contact <a className={LINK_CLASS} href="mailto:support@dormouse.sh">support@dormouse.sh</a> to request account closure or to ask us to review a restriction. When we close your account, we also cancel future subscription renewals. Before completing your closure request, we will explain when paid access will end and any refund available to you; you can instead cancel renewal and keep access through the paid period. Information is retained or deleted as described in the privacy policy and as required by law.</p>
  </> },
  { id: "responsibility", title: "Warranties and responsibility", body: <>
    <p>Consumers retain their mandatory rights to services that conform to the contract and are provided with reasonable care and skill, and any applicable remedies such as correction, a price reduction, or a refund. The qualifications below apply only where the law permits them.</p>
    <p>To the extent permitted by law, the service is provided “as is” and “as available,” without implied warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
    <p>To the extent permitted by law, DiffPlug LLC is not liable for indirect or consequential losses arising from the service. Its total aggregate liability for all claims arising out of or relating to these terms or Hosted is limited to the Hosted subscription fees you paid, including through our payment processor, in the twelve months preceding the first event giving rise to the claims. This is one aggregate limit, not a separate limit for each claim.</p>
    <p>The exclusions and limit do not reduce refunds owed under these terms, or exclude or limit liability for fraud, willful misconduct, gross negligence, death or personal injury caused by negligence, or any liability or consumer right that cannot lawfully be excluded or limited. You remain responsible for keeping independent copies of information you need.</p>
  </> },
  { id: "changes", title: "Changes and contact", body: <>
    <p>We will identify the effective date of changes on this page. We will give at least 30 days’ advance notice by email of material changes, except when an urgent security or legal need requires earlier action. Changes do not apply retroactively to disputes. If a material change takes effect during a prepaid term and you do not accept it, you may end your subscription and receive a refund for the unused portion. We will obtain renewed agreement where required by law.</p>
    <p>We may change monthly and yearly subscription prices only from a future renewal, after notice of the new price and how to cancel. We will give the notices required where you live, including applicable renewal reminders, annual reminders, and price-change notices. A price change never changes a founder’s locked base subscription price.</p>
    <p>For questions about these terms, contact DiffPlug LLC at <a className={LINK_CLASS} href="mailto:support@dormouse.sh">support@dormouse.sh</a>.</p>
    <p>Our business and postal address is DiffPlug LLC, 447 Sutter St Ste 405, San Francisco, CA 94108, United States.</p>
  </> },
];

export default function Terms() {
  return <HostedPolicyLayout path="/terms" title="Dormouse Hosted terms of service" sections={TERMS_SECTIONS} />;
}
