version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch-days: 1
      semver-minor-days: 3
      semver-major-days: 14
    versioning-strategy: "increase-if-necessary"
    groups:
      npm-production:
        dependency-type: "production"
        patterns:
          - "*"
      npm-development:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/standalone/src-tauri"
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch-days: 1
      semver-minor-days: 3
      semver-major-days: 14
    versioning-strategy: "increase-if-necessary"
    groups:
      cargo:
        patterns:
          - "*"
