packages:
  - dor
  - dor-lib-common
  - lib
  - standalone
  - standalone/sidecar
  - vscode-ext
  - website
allowBuilds:
  "@swc/core": true
  "@vscode/vsce-sign": false
  esbuild: true
  keytar: false
  node-pty: true
  sharp: true
peerDependencyRules:
  allowedVersions:
    "react-helmet-async>react": ^19.0.0
    "react-helmet-async>react-dom": ^19.0.0
minimumReleaseAge: 1440
