#!/usr/bin/env node
/**
 * Mechanical checks for the spec-suite conventions in AGENTS.md ("Specs" and
 * "Spec lifecycle"). Runs from the repo root via `pnpm test` (see the root
 * package.json). Exits non-zero with a per-violation report.
 *
 * Checks:
 *   1. Every docs/specs/*.md file is indexed in AGENTS.md.
 *   2. `## Future` (or `## N. Future`), when present, is the LAST section of
 *      its spec — the fold convention.
 *   3. Every relative markdown link in AGENTS.md + SELF_HOST.md + docs/specs
 *      resolves: the target file exists, and a `#fragment` matches a real
 *      heading anchor.
 *   4. Every backticked repo path mentioned in AGENTS.md + SELF_HOST.md +
 *      docs/specs exists on disk — catches `Source of truth:` pointers
 *      rotting on renames.
 *      Conservative: only tokens that start with a known top-level directory
 *      and contain no globs/placeholders are checked. Build outputs that only
 *      exist after a build are skipped via SKIP_PATH_PREFIXES.
 *   5. Every spec that uses glossary vocabulary (Session / Pane / Door /
 *      baseboard / passthrough) leads with a `> See docs/specs/glossary.md`
 *      blockquote. Scoped to docs/specs (SELF_HOST.md is a deployment spec;
 *      its lone incidental "baseboard" doesn't warrant the callout).
 *   6. A named scope (`**Scope: X**` leading a line) is defined exactly once
 *      across the corpus, and every bold reference — `(**Scope: X**)` or the
 *      bare `the **x** scope` form — names a defined scope.
 *   7. Every `Reserved:` paragraph names `## Future` or a defined scope — the
 *      Reservations convention in AGENTS.md.
 *   8. Every `<foo>.rationale.md` pairs with an existing `<foo>.md`, keys its
 *      entries by that spec's headings (each rationale `## X` must exist as a
 *      heading in the spec), and has no `## Future` — rationale files are
 *      informative, the fold belongs to the spec. Rationale files are not
 *      specs: they skip checks 1, 2, and 5 but ride 3 and 4.
 *   9. A spec uses one implementation map: either `## Files` / `## Code Map`
 *      or section-local `Source of truth:` pointers, never both.
 *  10. Word-budget ratchet: every checked file stays under its budget in
 *      scripts/spec-word-budgets.json. Growth past the budget fails; the fix
 *      is to cut, or to raise the budget deliberately in the same PR. Budgets
 *      carry small headroom so routine edits don't trip it. Words are counted
 *      by scripts/spec-words.mjs, which ignores table plumbing.
 *  11. Every `(rationale)` marker in a spec sits under a heading (or an
 *      ancestor heading) that has an entry in the paired rationale file — a
 *      marker asserts the evidence lives there. A spec with markers but no
 *      rationale file fails.
 *  12. A `Source of truth:` paragraph names at least one repo path check 4
 *      can verify, never a bare file name (`Wall.tsx` dodges check 4 and
 *      rots silently), and every `symbol` it places `in` a file exists in
 *      that file.
 *  13. Every citation of a spec section — `docs/specs/foo.md -> "Heading"`,
 *      `→ Heading`, `§Heading`, or `` `## Future` `` — in a tracked source
 *      file or spec names a heading (quoted forms may also name a bolded
 *      phrase) that exists in the cited file. Code comments cite specs this
 *      way in hundreds of places and nothing else keeps them honest.
 *  14. A rationale file states no rule: no paragraph or bullet opens with a
 *      bolded imperative (**Never …**, **Must …**, …). Those belong in the
 *      spec.
 *  15. A spec of RATIONALE_REQUIRED_WORDS or more has a rationale file;
 *      without one every piece of evidence sits above the fold and the
 *      ratchet cannot see it.
 */
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { countWords } from './spec-words.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SPECS_DIR = 'docs/specs';

const TOP_LEVEL_DIRS = [
  'lib/', 'standalone/', 'vscode-ext/', 'website/', 'server/',
  'server-lib-common/', 'dor/', 'dor-lib-common/', 'canopy/', 'docs/',
  'scripts/', 'deploy/', '.github/', '.claude/', '.vscode/',
];
// Path prefixes that are legitimate references to build/staged/generated
// output which does not exist in a clean checkout.
const SKIP_PATH_PREFIXES = [
  'lib/dist', 'dor/dist', 'vscode-ext/dist', 'vscode-ext/media',
  'standalone/dist',
  'website/src/data/changelog.json', // gitignored, generated by website prebuild (deploy.md)
  'canopy/node_modules', // created by pnpm install; lint:specs must pass on a fresh checkout (webgl-text.md)
];

const specDirFiles = readdirSync(join(ROOT, SPECS_DIR))
  .filter((f) => f.endsWith('.md'))
  // Keep repo-relative paths in POSIX form on every platform — they are
  // compared against forward-slash paths written in the markdown.
  .map((f) => `${SPECS_DIR}/${f}`);
const rationaleFiles = specDirFiles.filter((f) => f.endsWith('.rationale.md'));
const specFiles = specDirFiles.filter((f) => !f.endsWith('.rationale.md'));
// SELF_HOST.md is a root-level spec (the self-host deployment: runbook +
// installer contract); it rides checks 2-4 alongside the docs/specs files.
const allFiles = ['AGENTS.md', 'SELF_HOST.md', ...specFiles, ...rationaleFiles];
const foldCheckedFiles = ['SELF_HOST.md', ...specFiles];
const problems = [];

const read = (rel) => readFileSync(join(ROOT, rel), 'utf-8');

/** GitHub-style anchor slug for a heading title. */
function slug(title) {
  let t = title.trim().replace(/`/g, '');
  t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1'); // unwrap md links
  return t
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s/g, '-');
}

function headings(rel) {
  const out = [];
  let inFence = false;
  for (const line of read(rel).split('\n')) {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) continue;
    const m = /^(#{1,6})\s+(.*)$/.exec(line);
    if (m) out.push({ level: m[1].length, title: m[2].trim() });
  }
  return out;
}

/** Lines of a file with fenced code blocks blanked, for prose-only checks. */
function proseLines(rel) {
  let inFence = false;
  return read(rel).split('\n').map((line) => {
    if (/^\s*```/.test(line)) { inFence = !inFence; return ''; }
    return inFence ? '' : line;
  });
}

const anchorCache = new Map();
function anchorsOf(rel) {
  if (!anchorCache.has(rel)) {
    anchorCache.set(rel, new Set(headings(rel).map((h) => slug(h.title))));
  }
  return anchorCache.get(rel);
}

// --- Check 1: index completeness -------------------------------------------
const agents = read('AGENTS.md');
for (const spec of specFiles) {
  const base = spec.split('/').pop();
  if (!agents.includes(base)) {
    problems.push(`AGENTS.md: spec not indexed -> ${spec}`);
  }
}

// --- Check 2: Future is the last section ------------------------------------
for (const spec of foldCheckedFiles) {
  const h2s = headings(spec).filter((h) => h.level === 2);
  const futureIdx = h2s.findIndex((h) => /^(\d+\.\s*)?Future$/i.test(h.title));
  if (futureIdx !== -1 && futureIdx !== h2s.length - 1) {
    problems.push(
      `${spec}: "## ${h2s[futureIdx].title}" must be the last section ` +
      `(followed by "## ${h2s[futureIdx + 1].title}")`,
    );
  }
}

// --- Check 3: relative links + anchors resolve -------------------------------
const LINK_RE = /\]\(([^)\s]+)\)/g;
for (const rel of allFiles) {
  const base = dirname(rel);
  const lines = read(rel).split('\n');
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) return;
    for (const m of line.matchAll(LINK_RE)) {
      const target = m[1];
      if (/^(https?:|mailto:)/.test(target)) continue;
      const [path, fragment] = target.split('#');
      const full = path ? normalize(join(base, path)) : rel;
      if (path && !existsSync(join(ROOT, full))) {
        problems.push(`${rel}:${i + 1}: broken link -> ${target}`);
        continue;
      }
      if (fragment && full.endsWith('.md') && !anchorsOf(full).has(fragment)) {
        problems.push(`${rel}:${i + 1}: missing anchor -> ${target}`);
      }
    }
  });
}

// --- Check 4: backticked repo paths exist ------------------------------------
const TICK_RE = /`([^`\n]+)`/g;
for (const rel of allFiles) {
  const lines = read(rel).split('\n');
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) return;
    for (const m of line.matchAll(TICK_RE)) {
      const token = m[1];
      if (!token.includes('/')) continue;
      if (/[\s*{<>$%(?\\]|\.\.\.|…/.test(token)) continue;
      if (!TOP_LEVEL_DIRS.some((d) => token === d.slice(0, -1) || token.startsWith(d))) continue;
      if (SKIP_PATH_PREFIXES.some((p) => token.startsWith(p))) continue;
      if (!existsSync(join(ROOT, token))) {
        problems.push(`${rel}:${i + 1}: path does not exist -> ${token}`);
      }
    }
  });
}

// --- Check 5: glossary callout for specs using glossary vocabulary -----------
// Conservative match: the capitalized glossary senses plus the two words that
// are dormouse-specific in any case. Lowercase "session"/"pane" prose and
// compounds like `PersistedPane` do not trigger.
const GLOSSARY_VOCAB = /\b(?:Pane|Door|Session|[Bb]aseboard|passthrough)\b/;
for (const spec of specFiles) {
  if (spec.endsWith('/glossary.md')) continue;
  const lines = proseLines(spec);
  const firstH2 = lines.findIndex((l) => /^##\s/.test(l));
  const head = lines.slice(0, firstH2 === -1 ? lines.length : firstH2);
  if (head.some((l) => l.startsWith('>') && l.includes('glossary.md'))) continue;
  const hit = lines.findIndex((l) => GLOSSARY_VOCAB.test(l));
  if (hit !== -1) {
    problems.push(
      `${spec}:${hit + 1}: uses glossary vocabulary but has no leading ` +
      '"> See docs/specs/glossary.md ..." blockquote',
    );
  }
}

// --- Check 6: named scopes defined once; bold references resolve --------------
const SCOPE_RE = /\*\*Scope: ([a-z0-9-]+)\*\*/g;
// Cross-spec references also use the bare form ("the **dor-tools** scope"),
// which AGENTS.md sanctions with "other specs link to it by name".
const SCOPE_REF_RE = /\*\*([a-z0-9-]+)\*\* scope/g;
const scopeDefs = new Map(); // name -> "file:line" of the definition
const scopeRefs = [];
for (const rel of allFiles) {
  proseLines(rel).forEach((line, i) => {
    for (const m of line.matchAll(SCOPE_RE)) {
      if (m.index === 0) {
        // A definition leads its line; references are parenthesized mid-line.
        if (scopeDefs.has(m[1])) {
          problems.push(
            `${rel}:${i + 1}: scope "${m[1]}" already defined at ` +
            `${scopeDefs.get(m[1])} — a scope is defined in exactly one spec`,
          );
        } else {
          scopeDefs.set(m[1], `${rel}:${i + 1}`);
        }
      } else {
        scopeRefs.push({ rel, line: i + 1, name: m[1] });
      }
    }
    for (const m of line.matchAll(SCOPE_REF_RE)) {
      scopeRefs.push({ rel, line: i + 1, name: m[1] });
    }
  });
}
for (const ref of scopeRefs) {
  if (!scopeDefs.has(ref.name)) {
    problems.push(`${ref.rel}:${ref.line}: reference to undefined scope "${ref.name}"`);
  }
}

// --- Check 7: Reserved: names ## Future or a defined scope --------------------
for (const rel of allFiles) {
  const lines = proseLines(rel);
  lines.forEach((line, i) => {
    if (!/\bReserved:/.test(line)) return;
    // The paragraph: this line plus continuations, up to a blank line, a new
    // top-level bullet, or a heading.
    let para = line;
    for (let j = i + 1; j < lines.length; j++) {
      if (lines[j].trim() === '' || /^[-*]\s/.test(lines[j]) || /^#{1,6}\s/.test(lines[j])) break;
      para += '\n' + lines[j];
    }
    const named = /Future/.test(para) || [...scopeDefs.keys()].some((n) => para.includes(n));
    if (!named) {
      problems.push(
        `${rel}:${i + 1}: "Reserved:" paragraph names neither ## Future nor a defined scope`,
      );
    }
  });
}

// --- Check 8: rationale files pair with a spec and key by its headings --------
for (const rat of rationaleFiles) {
  const spec = rat.replace(/\.rationale\.md$/, '.md');
  if (!existsSync(join(ROOT, spec))) {
    problems.push(`${rat}: no paired spec -> ${spec}`);
    continue;
  }
  const specAnchors = anchorsOf(spec);
  for (const h of headings(rat).filter((h) => h.level === 2)) {
    if (/^(\d+\.\s*)?Future$/i.test(h.title)) {
      problems.push(`${rat}: rationale files are informative — the fold ("## Future") belongs to ${spec}`);
    } else if (!specAnchors.has(slug(h.title))) {
      problems.push(`${rat}: "## ${h.title}" is not a heading in ${spec}`);
    }
  }
}

// --- Check 9: one implementation map per spec -------------------------------
for (const spec of foldCheckedFiles) {
  const lines = proseLines(spec);
  const mapLine = lines.findIndex((line) => /^##\s+(?:Files|Code Map)\s*$/i.test(line));
  const sourceLine = lines.findIndex((line) => /\bSource of truth:/.test(line));
  if (mapLine !== -1 && sourceLine !== -1) {
    problems.push(
      `${spec}:${sourceLine + 1}: has both "${lines[mapLine].trim()}" and ` +
      '`Source of truth:` pointers — use one implementation map',
    );
  }
}

// --- Check 10: word-budget ratchet ------------------------------------------
const BUDGETS_FILE = 'scripts/spec-word-budgets.json';
const budgets = JSON.parse(read(BUDGETS_FILE));
for (const rel of allFiles) {
  const words = countWords(read(rel));
  const budget = budgets[rel];
  if (budget === undefined) {
    problems.push(`${BUDGETS_FILE}: no budget for ${rel} — add one (currently ${words} words)`);
  } else if (words > budget) {
    problems.push(
      `${rel}: ${words} words exceeds its ${budget}-word budget — cut, ` +
      `or raise the budget in ${BUDGETS_FILE} deliberately in the same PR`,
    );
  }
}
for (const rel of Object.keys(budgets)) {
  if (!allFiles.includes(rel)) {
    problems.push(`${BUDGETS_FILE}: stale entry for missing file ${rel}`);
  }
}

// --- Check 11: (rationale) markers sit under a heading the rationale keys -----
// A marker is the word `rationale` on its own inside a parenthetical:
// `(rationale)`, `(rationale; …)`, `(…; rationale)`. A continuation line that
// closes a parenthetical opened on the line before also counts.
const MARKER_RE = /\((?:[^()]*;\s*)?rationale(?:\s*;[^()]*)?\)|^[^()]*\brationale\)/;
for (const spec of specFiles) {
  const rat = spec.replace(/\.md$/, '.rationale.md');
  const hasRat = existsSync(join(ROOT, rat));
  const keys = hasRat
    ? new Set(headings(rat).filter((h) => h.level === 2).map((h) => slug(h.title)))
    : new Set();
  const stack = [];
  proseLines(spec).forEach((line, i) => {
    const h = /^(#{1,6})\s+(.*)$/.exec(line);
    if (h) {
      const level = h[1].length;
      while (stack.length && stack[stack.length - 1].level >= level) stack.pop();
      stack.push({ level, slug: slug(h[2]) });
      return;
    }
    if (!MARKER_RE.test(line)) return;
    if (!hasRat) {
      problems.push(`${spec}:${i + 1}: "(rationale)" marker, but ${rat} does not exist`);
    } else if (!stack.some((s) => keys.has(s.slug))) {
      const under = stack.length ? stack[stack.length - 1].slug : '(no heading)';
      problems.push(
        `${spec}:${i + 1}: "(rationale)" marker under "${under}", but ${rat} has no ` +
        'entry under that heading or an ancestor of it',
      );
    }
  });
}

// --- Check 12: Source of truth paragraphs are checkable ---------------------
const isRepoPath = (t) => TOP_LEVEL_DIRS.some((d) => t.startsWith(d));
const BARE_BASENAME_RE = /^[\w.-]+\.(?:ts|tsx|js|mjs|cjs|rs|json|css|md|sh|ps1|ya?ml|html|toml)$/;
const IDENT_RE = /^[A-Za-z_$][\w$]*(?:[.#][\w$]+)*(?:\(\))?$/;
const SYMBOLS_IN_FILE_RE = new RegExp(
  '((?:`[^`\\n]+`\\s*(?:\\/|,|and|\\+)?\\s*)+)\\bin\\s+`((?:' +
  TOP_LEVEL_DIRS.map((d) => d.slice(0, -1).replace('.', '\\.')).join('|') +
  ')\\/[^`\\n]+)`',
  'g',
);
const sourceCache = new Map();
const sourceOf = (rel) => {
  if (!sourceCache.has(rel)) {
    sourceCache.set(rel, existsSync(join(ROOT, rel)) ? readFileSync(join(ROOT, rel), 'utf-8') : null);
  }
  return sourceCache.get(rel);
};
for (const spec of foldCheckedFiles) {
  const lines = proseLines(spec);
  lines.forEach((line, i) => {
    const at = line.indexOf('Source of truth:');
    if (at === -1) return;
    let para = line.slice(at);
    let j = i + 1;
    for (; j < lines.length; j++) {
      if (lines[j].trim() === '' || /^[-*]\s/.test(lines[j]) || /^#{1,6}\s/.test(lines[j])) break;
      para += '\n' + lines[j];
    }
    // `Source of truth:` may introduce a table; its rows are the pointers.
    while (j < lines.length && lines[j].trim() === '') j++;
    for (; j < lines.length && lines[j].trimStart().startsWith('|'); j++) para += '\n' + lines[j];
    const tokens = [...para.matchAll(TICK_RE)].map((m) => m[1]);
    if (!tokens.some(isRepoPath)) {
      problems.push(`${spec}:${i + 1}: Source of truth names no repo path the path check can verify`);
    }
    for (const t of tokens) {
      if (BARE_BASENAME_RE.test(t) && !existsSync(join(ROOT, t))) { // a root file is a path
        problems.push(`${spec}:${i + 1}: Source of truth names a bare file name \`${t}\` — use the full repo path`);
      }
    }
    for (const m of para.matchAll(SYMBOLS_IN_FILE_RE)) {
      const src = sourceOf(m[2]);
      if (src === null) continue; // check 4 reports the missing file
      for (const sym of [...m[1].matchAll(TICK_RE)].map((x) => x[1])) {
        if (!IDENT_RE.test(sym)) continue;
        const leaf = sym.replace(/\(\)$/, '').split(/[.#]/).pop();
        if (!src.includes(leaf)) {
          problems.push(`${spec}:${i + 1}: Source of truth places \`${sym}\` in \`${m[2]}\`, which does not contain it`);
        }
      }
    }
  });
}

// --- Check 13: spec-section citations resolve, in specs and in code --------
// `docs/specs/foo.md -> "Heading"`, `→ Heading`, `§Heading`, `` `## Future` ``.
// Quoted text may also name a bolded phrase in the cited file; an unquoted
// reference must name a heading (a heading may be a prefix of the captured
// text, since the citation often runs on).
const CITATION_RE = /(docs\/specs\/[a-z-]+\.md|SELF_HOST\.md|SECURITY\.md|AGENTS\.md)[`)\]]*\s*(?:(?:->|→)\s*(?:"([^"]+)"|`(#{1,6}\s[^`]+)`|([A-Z][^"`.,;:()\n]*))|§\s*([^.,;:()\n]+))/g;
const CITING_FILE_RE = /\.(?:ts|tsx|js|mjs|cjs|rs|ya?ml|sh|ps1|md|toml|json)$/;
// ASCII and Unicode arrows are the same citation.
const norm = (text) => text.replace(/↔/g, '<->').replace(/→/g, '->');
const citeTargets = new Map();
const citeTarget = (rel) => {
  if (!citeTargets.has(rel)) {
    citeTargets.set(rel, existsSync(join(ROOT, rel))
      ? { text: norm(read(rel)), heads: headings(rel).map((h) => norm(h.title)) }
      : null);
  }
  return citeTargets.get(rel);
};
const trackedFiles = execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8' })
  .trim().split('\n').filter((f) => CITING_FILE_RE.test(f) && f !== 'scripts/spec-lint.mjs');
for (const rel of trackedFiles) {
  let text;
  try { text = read(rel); } catch { continue; }
  if (!/docs\/specs\/|SELF_HOST\.md|SECURITY\.md|AGENTS\.md/.test(text)) continue;
  text.split('\n').forEach((line, i) => {
    for (const m of line.matchAll(CITATION_RE)) {
      const t = citeTarget(m[1]);
      if (!t) continue; // check 4 reports a missing spec
      const quoted = m[2] !== undefined;
      const ref = norm((m[2] ?? (m[3] !== undefined ? m[3].replace(/^#+\s*/, '') : (m[4] ?? m[5]))).trim());
      if (!ref) continue;
      const names = (r) => t.heads.some((h) => h.includes(r)) || t.text.includes(r);
      let ok;
      if (quoted) {
        ok = names(ref);
      } else {
        // An unquoted citation runs on into the sentence; shorten it word by
        // word; a single word must then name a heading outright.
        const words = ref.split(/\s+/);
        ok = false;
        for (let n = words.length; n >= 1 && !ok; n--) {
          const r = words.slice(0, n).join(' ');
          ok = n === 1 ? t.heads.some((h) => h.includes(r)) : names(r);
        }
      }
      if (!ok) {
        problems.push(
          `${rel}:${i + 1}: cites ${m[1]} -> "${ref}", which names no heading` +
          `${quoted ? ' or phrase' : ''} in that file`,
        );
      }
    }
  });
}

// --- Check 14: rationale files state no rule ---------------------------------
const BOLD_IMPERATIVE_RE = /^\s*(?:[-*]\s+)?\*\*(?:Never|Must|Always|May|Do not|Don['’]t|Should|Shall)\b/;
for (const rat of rationaleFiles) {
  proseLines(rat).forEach((line, i) => {
    if (BOLD_IMPERATIVE_RE.test(line)) {
      problems.push(`${rat}:${i + 1}: opens with a bolded imperative — rules live in the spec, not the rationale`);
    }
  });
}

// --- Check 15: a large spec has a rationale file -----------------------------
const RATIONALE_REQUIRED_WORDS = 2500;
for (const spec of specFiles) {
  const rat = spec.replace(/\.md$/, '.rationale.md');
  if (existsSync(join(ROOT, rat))) continue;
  const words = countWords(read(spec));
  if (words >= RATIONALE_REQUIRED_WORDS) {
    problems.push(`${spec}: ${words} words and no ${rat} — its evidence has nowhere to go but above the fold`);
  }
}

// -----------------------------------------------------------------------------
if (problems.length > 0) {
  console.error(`spec-lint: ${problems.length} problem(s)\n`);
  for (const p of problems) console.error(`  ${p}`);
  console.error(
    '\nConventions are defined in AGENTS.md ("Specs" and "Spec lifecycle").',
  );
  process.exit(1);
}
console.log(`spec-lint: OK (${specFiles.length} specs, ${allFiles.length} files checked)`);
