#!/usr/bin/env node
/**
 * Mechanical checks for the spec-suite conventions in AGENTS.md ("Specs" and
 * "Spec lifecycle"). Runs from the repo root via `pnpm test` (see the root
 * package.json). Exits non-zero with a per-violation report.
 *
 * Checks:
 *   1. Every docs/specs/*.md file is indexed in AGENTS.md.
 *   2. `## Future` (or `## N. Future`), when present, is the LAST section of
 *      its spec — the fold convention.
 *   3. Every relative markdown link in AGENTS.md + docs/specs resolves: the
 *      target file exists, and a `#fragment` matches a real heading anchor.
 *   4. Every backticked repo path mentioned in AGENTS.md + docs/specs exists
 *      on disk — catches `Source of truth:` pointers rotting on renames.
 *      Conservative: only tokens that start with a known top-level directory
 *      and contain no globs/placeholders are checked. Build outputs that only
 *      exist after a build are skipped via SKIP_PATH_PREFIXES.
 */
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SPECS_DIR = 'docs/specs';

const TOP_LEVEL_DIRS = [
  'lib/', 'standalone/', 'vscode-ext/', 'website/', 'server/',
  'server-lib-common/', 'dor/', 'dor-lib-common/', 'docs/', 'scripts/',
  '.github/', '.claude/', '.vscode/',
];
// Path prefixes that are legitimate references to build/staged/generated
// output which does not exist in a clean checkout.
const SKIP_PATH_PREFIXES = [
  'lib/dist', 'dor/dist', 'vscode-ext/dist', 'vscode-ext/media',
  'standalone/dist',
  'website/src/data/changelog.json', // gitignored, generated by website prebuild (deploy.md)
];

const specFiles = readdirSync(join(ROOT, SPECS_DIR))
  .filter((f) => f.endsWith('.md'))
  // Keep repo-relative paths in POSIX form on every platform — they are
  // compared against forward-slash paths written in the markdown.
  .map((f) => `${SPECS_DIR}/${f}`);
const allFiles = ['AGENTS.md', ...specFiles];
const problems = [];

const read = (rel) => readFileSync(join(ROOT, rel), 'utf-8');

/** GitHub-style anchor slug for a heading title. */
function slug(title) {
  let t = title.trim().replace(/`/g, '');
  t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1'); // unwrap md links
  return t
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s/g, '-');
}

function headings(rel) {
  const out = [];
  let inFence = false;
  for (const line of read(rel).split('\n')) {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) continue;
    const m = /^(#{1,6})\s+(.*)$/.exec(line);
    if (m) out.push({ level: m[1].length, title: m[2].trim() });
  }
  return out;
}

const anchorCache = new Map();
function anchorsOf(rel) {
  if (!anchorCache.has(rel)) {
    anchorCache.set(rel, new Set(headings(rel).map((h) => slug(h.title))));
  }
  return anchorCache.get(rel);
}

// --- Check 1: index completeness -------------------------------------------
const agents = read('AGENTS.md');
for (const spec of specFiles) {
  const base = spec.split('/').pop();
  if (!agents.includes(base)) {
    problems.push(`AGENTS.md: spec not indexed -> ${spec}`);
  }
}

// --- Check 2: Future is the last section ------------------------------------
for (const spec of specFiles) {
  const h2s = headings(spec).filter((h) => h.level === 2);
  const futureIdx = h2s.findIndex((h) => /^(\d+\.\s*)?Future$/i.test(h.title));
  if (futureIdx !== -1 && futureIdx !== h2s.length - 1) {
    problems.push(
      `${spec}: "## ${h2s[futureIdx].title}" must be the last section ` +
      `(followed by "## ${h2s[futureIdx + 1].title}")`,
    );
  }
}

// --- Check 3: relative links + anchors resolve -------------------------------
const LINK_RE = /\]\(([^)\s]+)\)/g;
for (const rel of allFiles) {
  const base = dirname(rel);
  const lines = read(rel).split('\n');
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) return;
    for (const m of line.matchAll(LINK_RE)) {
      const target = m[1];
      if (/^(https?:|mailto:)/.test(target)) continue;
      const [path, fragment] = target.split('#');
      const full = path ? normalize(join(base, path)) : rel;
      if (path && !existsSync(join(ROOT, full))) {
        problems.push(`${rel}:${i + 1}: broken link -> ${target}`);
        continue;
      }
      if (fragment && full.endsWith('.md') && !anchorsOf(full).has(fragment)) {
        problems.push(`${rel}:${i + 1}: missing anchor -> ${target}`);
      }
    }
  });
}

// --- Check 4: backticked repo paths exist ------------------------------------
const TICK_RE = /`([^`\n]+)`/g;
for (const rel of allFiles) {
  const lines = read(rel).split('\n');
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) return;
    for (const m of line.matchAll(TICK_RE)) {
      const token = m[1];
      if (!token.includes('/')) continue;
      if (/[\s*{<>$%(?\\]|\.\.\.|…/.test(token)) continue;
      if (!TOP_LEVEL_DIRS.some((d) => token === d.slice(0, -1) || token.startsWith(d))) continue;
      if (SKIP_PATH_PREFIXES.some((p) => token.startsWith(p))) continue;
      if (!existsSync(join(ROOT, token))) {
        problems.push(`${rel}:${i + 1}: path does not exist -> ${token}`);
      }
    }
  });
}

// -----------------------------------------------------------------------------
if (problems.length > 0) {
  console.error(`spec-lint: ${problems.length} problem(s)\n`);
  for (const p of problems) console.error(`  ${p}`);
  console.error(
    '\nConventions are defined in AGENTS.md ("Specs" and "Spec lifecycle").',
  );
  process.exit(1);
}
console.log(`spec-lint: OK (${specFiles.length} specs, ${allFiles.length} files checked)`);
