name: Chromatic

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
  pull_request:
    paths:
      - 'lib/**'

jobs:
  chromatic:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
        with:
          version: 11.0.6

      - name: Install dependencies
        run: pnpm install
        working-directory: lib

      - name: Run Chromatic
        uses: chromaui/action@1fd1c4b0d4411b6de61818251f04b047850bf500 # latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: lib
          buildScriptName: build-storybook
          exitZeroOnChanges: true
          onlyChanged: true
